Repository politecnicoDAW-2022/DIW-Proyecto-Gropy, pull requests merged in 2022-11, with the labels that each got.

#51 Add github action to sort alphabetical atributes on css
  .prettierrc
  CHANGELOG.md
  assets/styles/style.css
  package-lock.json
  package.json
Labels: Enhancement, Github

#34 Feat(change header size when scrolling)
  assets/styles/style.css
  index.html
  package-lock.json
  scroll.js
Labels: Enhancement, Frontend, UX/UI

#52 refactor: scroll animations
  CHANGELOG.md
  app.js
  assets/js/scroll.js
  assets/styles/style.css
  index.html
  scroll.js
Labels: Frontend, UX/UI

#54 Added css to plans section
  CHANGELOG.md
  assets/styles/main.scss
  assets/styles/sass/02-components/_plans.scss
  assets/styles/style.css
  components/plans.html
Labels: Enhancement, UX/UI
